### ISSUE TITLE
error on file run

### ISSUE THREAD

**Issue by Cooperzilla** [vivaansinghvi07/dreamberd-interpreter#21]
i'm on ubuntu wsl with python `3.10.12` I get an error on attempting to run a file

i ran the install command `pip install dreamberd` and i also tryed running it with pip3 and uninstalling

and i got the logs of 
```
Defaulting to user installation because normal site-packages is not writeable
Collecting dreamberd
  Using cached dreamberd-0.1.1-py3-none-any.whl (48 kB)
Requirement already satisfied: requests==2.31.0 in /home/cooper/.local/lib/python3.10/site-packages (from dreamberd) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/cooper/.local/lib/python3.10/site-packages (from requests==2.31.0->dreamberd) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.31.0->dreamberd) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.31.0->dreamberd) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.31.0->dreamberd) (2020.6.20)
Installing collected packages: dreamberd
Successfully installed dreamberd-0.1.1
```

// index.db
`print("hello world")!`

// the command ran
`dreamberd index.db`
I also get the error with the help command `dreamberd --help`

// the error
```
Traceback (most recent call last):
  File "/home/cooper/.local/bin/dreamberd", line 5, in <module>
    from dreamberd import main
  File "/home/cooper/.local/lib/python3.10/site-packages/dreamberd/__init__.py", line 11, in <module>
    from dreamberd.interpreter import interpret_code_statements, interpret_code_statements_main_wrapper, load_global_dreamberd_variables, load_globals, load_public_global_variables
  File "/home/cooper/.local/lib/python3.10/site-packages/dreamberd/interpreter.py", line 37, in <module>
    from dreamberd.serialize import serialize_obj, deserialize_obj
  File "/home/cooper/.local/lib/python3.10/site-packages/dreamberd/serialize.py", line 3, in <module>
    from typing import Any, Callable, Type, Union, assert_never
ImportError: cannot import name 'assert_never' from 'typing' (/usr/lib/python3.10/typing.py)
```

**Comment by vivaansinghvi07** [comment]
It seems that `assert_never` was added in Python3.11 and therefore raises an error in Python3.10. For a quick fix, navigate to the file `/home/cooper/.local/lib/python3.10/site-packages/dreamberd/serialize.py`, remove the import for `assert_never`, and replace its two calls with the keyword `pass` (lines `41` and `75`).

**Comment by Cooperzilla** [comment]
thank you that fixed it
