### ISSUE TITLE
Error caused by assigning any variable

### ISSUE THREAD

**Issue by ThePython10110** [vivaansinghvi07/dreamberd-interpreter#24]
Assigning any variable seems to cause an error:
```
> var var a = 1
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python311\Scripts\dreamberd.exe\__main__.py", line 7, in <module>
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dreamberd\__init__.py", line 119, in main
    run_repl()
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dreamberd\__init__.py", line 57, in run_repl
    interpret_code_statements(statements, namespaces, async_statements, when_statement_watchers)
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dreamberd\interpreter.py", line 1474, in interpret_code_statements
    elif retval := interpret_statement(statement, namespaces, async_statements, when_statement_watchers):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dreamberd\interpreter.py", line 1276, in interpret_statement
    built_expr = get_built_expression(expr)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dreamberd\interpreter.py", line 65, in get_built_expression
    return expr if isinstance(expr, ExpressionTreeNode) else build_expression_tree(filename, expr, code)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dreamberd\processor\expression_tree.py", line 140, in build_expression_tree
    starts_with_operator = int(tokens_without_whitespace[0].type in {TokenType.SEMICOLON, TokenType.SUBTRACT})
                               ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Through some effort, I found that the expression passed to that function is `[[Token(TokenType.WHITESPACE, ' ')]]`

Since the only token is whitespace, it fails.

**Comment by vivaansinghvi07** [comment]
Apologies for the late response. I think this is because you need to end each statement with a `!` in the REPL or it breaks.

**Comment by ThePython10110** [comment]
Ah, AEMI hasn't been implemented yet?
