### ISSUE TITLE
After and await seem to not work correctly

### ISSUE THREAD

**Issue by JanEricNitschke** [vivaansinghvi07/dreamberd-interpreter#30]
I wanted to run this example from the readme:

```
const var score = 5!
after ("click") { score = score + 1! }
print(await next score)!
```

and first got an error that "click" is an invalid event. I had a look at the code and it looks like the correct one is "mouseclick".
But even with that i get an error

```
$ dreamberd tictactoe.db
IndexError: list index out of range
```

**Comment by JanEricNitschke** [comment]
Here is the full python traceback:

```
 dreamberd -s tictactoe.db
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\users\jan-eric\.local\bin\dreamberd.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\__init__.py", line 126, in main
    run_file(args.file)
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\__init__.py", line 98, in run_file
    interpret_code_statements_main_wrapper(statements, namespaces, [], [{}])
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1509, in interpret_code_statements_main_wrapper
    interpret_code_statements(statements, namespaces, async_statements, when_statement_watchers)
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1474, in interpret_code_statements
    elif retval := interpret_statement(statement, namespaces, async_statements, when_statement_watchers):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1329, in interpret_statement
    val = evaluate_expression(statement.expression, namespaces, async_statements, when_statement_watchers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 722, in evaluate_expression
    retval = evaluate_expression_for_real(expr, namespaces, async_statements, when_statement_watchers, ignore_string_escape_sequences)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 797, in evaluate_expression_for_real
    return evaluate_normal_function(expr, func.value, namespaces, args, when_statement_watchers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 87, in evaluate_normal_function
    return interpret_code_statements(func.code, namespaces + [new_namespace], [], when_statement_watchers + [{}]) or DreamberdUndefined()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1474, in interpret_code_statements
    elif retval := interpret_statement(statement, namespaces, async_statements, when_statement_watchers):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1329, in interpret_statement
    val = evaluate_expression(statement.expression, namespaces, async_statements, when_statement_watchers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 722, in evaluate_expression
    retval = evaluate_expression_for_real(expr, namespaces, async_statements, when_statement_watchers, ignore_string_escape_sequences)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 797, in evaluate_expression_for_real
    return evaluate_normal_function(expr, func.value, namespaces, args, when_statement_watchers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 87, in evaluate_normal_function
    return interpret_code_statements(func.code, namespaces + [new_namespace], [], when_statement_watchers + [{}]) or DreamberdUndefined()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1474, in interpret_code_statements
    elif retval := interpret_statement(statement, namespaces, async_statements, when_statement_watchers):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1303, in interpret_statement
    namespaces[-1] |= (prev_namespace := prev_namespace | wait_for_async_nexts(all_async_nexts, namespaces))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan-Eric\pipx\venvs\dreamberd\Lib\site-packages\dreamberd\interpreter.py", line 1102, in wait_for_async_nexts
    new_namespace[mod_name] = Name(mod_name, v.prev_values[i])
                                             ~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by vivaansinghvi07** [comment]
I appreciate you finding all these issues! I’ll have them fixed soon

**Comment by JanEricNitschke** [comment]
Awesome, thanks! If you have any pointers i could also try to take one of these issues. I tried to start with the "await next" but didnt manage to properly understand all of the code yet.

**Comment by JanEricNitschke** [comment]
And just for reference, this is the program i am trying to run:

```
const var board = Map()!
board["0"] = 0!
board["1"] = 1!
board["2"] = 2!
board["3"] = 3!
board["4"] = 4!
board["5"] = 5!
board["6"] = 6!
board["7"] = 7!
board["8"] = 8!

var const player = "X"!
var var done = false!

funci game_won(game_board) => {
   if (game_board["0"]===player & game_board["1"]===player & game_board["2"]===player) {
      return true!
   }
   if (game_board["3"]===player & game_board["4"]===player & game_board["5"]===player) {
      return true!
   }
   if (game_board["6"]===player & game_board["7"]===player & game_board["8"]===player) {
      return true!
   }
   if (game_board["0"]===player & game_board["3"]===player & game_board["6"]===player) {
      return true!
   }
   if (game_board["1"]===player & game_board["4"]===player & game_board["7"]===player) {
      return true!
   }
   if (game_board["2"]===player & game_board["5"]===player & game_board["8"]===player) {
      return true!
   }
   if (game_board["0"]===player & game_board["4"]===player & game_board["8"]===player) {
      return true!
   }
   if (game_board["2"]===player & game_board["4"]===player & game_board["6"]===player) {
      return true!
   }
   return false!
}

funci board_full(game_board) => {
   return game_board["0"];===0 & game_board["1"];===1 & game_board["2"];===2 & game_board["3"];===3 & game_board["4"];===4 & game_board["5"];===5 & game_board["6"];===6 & game_board["7"];===7 & game_board["8"];===8!
}

funci player_turn() => {
   print ("Player €{player} enter your move (0-8)!")!
   show_board()!
   await  next board!
}

funci swap_player() => {
   if (player === "X") {
      player = "O"!
   }
   if (player === "O") {
      player = "X"!
   }
}

funci show_board() => {
   print ( board["0"] + " | " + board["1"] + " | " + board["2"])!
   print  ("---------")!
   print ( board["3"] + " | " + board["4"] + " | " + board["5"])!
   print  ("---------")!
   print ( board["6"] + " | " + board["7"] + " | " + board["8"])!

   print  ('€{board["0"]} | €{board["1"]} | €{board["2"]}')!
   print  ("---------")!
   print  ('€{board["3"]} | €{board["4"]} | €{board["5"]}')!
   print  ("---------")!
   print  ('€{board["6"]} | €{board["7"]} | €{board["8"]}')!
}

funci play() => {
   player_turn()!
   swap_player()!
   play()!
}

after "keyclick" {
   print(event.key)!
   board[event.key] = player!
}

when (game_won(board) === true) {
   print("Player €{player} wins the game!)!
   show_board()!
   exit()!
}

when (board_full(board) === true) {
   print("Game Drawn!)!
   show_board()!
   exit()!
}

play()!

```

**Comment by JanEricNitschke** [comment]
Made PRs to fix all of the others, but this one is still a bit too deep into complicated logic for me.

**Comment by JanEricNitschke** [comment]
Got it to generally work now. Now i am stuck on my larger program again.

Whenever i perform a keyclick to make a move, the when check is performed BEFORE the board has been updated. Additionally, it seems to just go right back to waiting instead of continuing in my gameplay loop.

**Comment by vivaansinghvi07** [comment]
Sorry for the late reply (was on a break), but thank you for all the work you've done so far! I've merged all your other PRs, and it looks like your modifications to the code in the second to last reply are all spot on. Regarding your last reply, I agree on your description of where the bug is happening:

```python3
when_watchers = get_code_from_when_statement_watchers(id(value_to_modify), when_statement_watchers)
for when_watcher in when_watchers:  # i just wanna be done with this :(
    if any([when_watcher == x for x in visited_whens]): 
        continue
    condition, inside_statements = when_watcher
    condition_val = evaluate_expression(condition, namespaces, async_statements, when_statement_watchers)
    execute_conditional(condition_val, inside_statements, namespaces, when_statement_watchers)
    visited_whens.append(when_watcher)

if not remaining_indexes:  # perform actual assignment here
    value_to_modify.assign_index(index, new_value)
else:
    assign_variable_helper(value_to_modify.access_index(index), remaining_indexes)

```

I think this could be alleviated by moving things so that it is:

```python3
if not remaining_indexes:  # perform actual assignment here
    value_to_modify.assign_index(index, new_value)
else:
    assign_variable_helper(value_to_modify.access_index(index), remaining_indexes)

when_watchers = get_code_from_when_statement_watchers(id(value_to_modify), when_statement_watchers)
for when_watcher in when_watchers:  # i just wanna be done with this :(
    if any([when_watcher == x for x in visited_whens]): 
        continue
    condition, inside_statements = when_watcher
    condition_val = evaluate_expression(condition, namespaces, async_statements, when_statement_watchers)
    execute_conditional(condition_val, inside_statements, namespaces, when_statement_watchers)
    visited_whens.append(when_watcher)

```

Feel free to make all this into a PR (or let me know if there's another issue) if you want!

**Comment by JanEricNitschke** [comment]
Thanks a ton! And dont feel any pressure from me, i realize that this is a "for fun" hobby project, but i am very grateful that it is there for use in my own :).

I am currently working on a [branch](https://github.com/JanEricNitschke/dreamberd-interpreter/tree/new-main) when i added pre-commit and did formatting and so on. So i will move these changes afterwards into something you can easily merge here.

I found another thing that was stopping my program from working but i think that was just my mistake. Changing an entry in a list wasnt actually adding to its previous values and so the await next never finished. I have now added a helper variable for that but encoutnered another issue. Will let you know when i understand what is happening.

**Comment by JanEricNitschke** [comment]
Got a fully working version now: https://github.com/JanEricNitschke/TicTacToe/actions/runs/11386283921/job/31678124278#step:5:21

Will swap this to your PyPI hosted one once it has everything in that i need.
